package router

import (
	_ "GoModDemo/docs"
	"GoModDemo/middleware/jwt"
	"GoModDemo/service/api"

	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

//InitRouter 注册路由
func InitRouter() *gin.Engine {

	gin.SetMode(gin.ReleaseMode)
	gin.DisableBindValidation()
	router := gin.New()
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	loginVersionOne := router.Group("/")
	loginVersionOne.POST("Login", api.Login)
	testVersionOne := router.Group("/test")
	testVersionOne.GET("hello", api.IndexApi)
	userOne := router.Group("/User")
	userOne.Use(jwt.Jwt())
	userOne.POST("GetUserByID", api.GetUserByID)
	userOne.POST("GetUserMenu", api.GetUserMenu)
	userOne.POST("GetAllUserInfo", api.GetAllUserInfo)
	userOne.POST("GetAllUserViewInfo", api.GetAllUserViewInfo)
	userOne.POST("GetUserLogininfoByToken", api.GetUserLogininfoByToken)
	userOne.POST("AddUser", api.AddUser)
	userOne.POST("UpdateUser", api.UpdateUser)
	userOne.POST("DeleteUser", api.DeleteUser)
	userOne.POST("SetUserDept", api.SetUserDept)
	userOne.POST("SetUserRole", api.SetUserRole)
	userOne.POST("GetTreeUser", api.GetTreeUser)
	menuOne := router.Group("/Menu")
	menuOne.POST("GetMenuByID", api.GetMenuByID)
	menuOne.POST("GetAllMenuInfo", api.GetAllMenuInfo)
	menuOne.POST("GetAllMenuViewInfo", api.GetAllMenuViewInfo)
	menuOne.POST("GetCascaderMenu", api.GetCascaderMenu)
	menuOne.POST("GetMenuAllCount", api.GetMenuAllCount)
	menuOne.POST("AddMenu", api.AddMenu)
	menuOne.POST("UpdateMenu", api.UpdateMenu)
	menuOne.POST("DeleteMenu", api.DeleteMenu)
	menuOne.POST("SetMenuButton", api.SetMenuButton)
	buttonOne := router.Group("/Button")
	buttonOne.POST("GetButtonByMenuIdAndUserId", api.GetButtonByMenuIdAndUserId)
	buttonOne.POST("GetAllButtonForTransfer", api.GetAllButtonForTransfer)
	buttonOne.POST("GetButtonByMenuIdnForTransfer", api.GetButtonByMenuIdnForTransfer)
	buttonOne.POST("GetAllButtonByMenuIdForTransfer", api.GetAllButtonByMenuIdForTransfer)
	buttonOne.POST("GetButtonByMenuIdRoleIdForTransfer", api.GetButtonByMenuIdRoleIdForTransfer)
	buttonOne.POST("AddButton", api.AddButton)
	buttonOne.POST("UpdateButton", api.UpdateButton)
	buttonOne.POST("DeleteButton", api.DeleteButton)
	buttonOne.POST("GetAllButtonInfo", api.GetAllButtonInfo)
	buttonOne.POST("GetButtonByID", api.GetButtonByID)
	buttonOne.POST("GetButtonAllCount", api.GetButtonAllCount)
	deptOne := router.Group("/Dept")
	deptOne.POST("GetAllDeptForTransfer", api.GetAllDeptForTransfer)
	deptOne.POST("GetDeptByUserIdForTransfer", api.GetDeptByUserIdForTransfer)
	deptOne.POST("AddDept", api.AddDept)
	deptOne.POST("UpdateDept", api.UpdateDept)
	deptOne.POST("DeleteDept", api.DeleteDept)
	deptOne.POST("GetAllDeptInfo", api.GetAllDeptInfo)
	deptOne.POST("GetAllDeptViewInfo", api.GetAllDeptViewInfo)
	deptOne.POST("GetDeptByID", api.GetDeptByID)
	deptOne.POST("GetCascaderDept", api.GetCascaderDept)
	deptOne.POST("GetDeptAllCount", api.GetDeptAllCount)
	roleOne := router.Group("/Role")
	roleOne.POST("GetAllRoleForTransfer", api.GetAllRoleForTransfer)
	roleOne.POST("GetRoleByUserIdForTransfer", api.GetRoleByUserIdForTransfer)
	roleOne.POST("GetAllRoleInfo", api.GetAllRoleInfo)
	roleOne.POST("GetRoleByID", api.GetRoleByID)
	roleOne.POST("GetMenuByRoleIdForTree", api.GetMenuByRoleIdForTree)
	roleOne.POST("SetMenuRole", api.SetMenuRole)
	roleOne.POST("AddRole", api.AddRole)
	roleOne.POST("UpdateRole", api.UpdateRole)
	roleOne.POST("DeleteRole", api.DeleteRole)
	roleOne.POST("SetButtonByMenuIdRoleId", api.SetButtonByMenuIdRoleId)
	parameterOne := router.Group("/Parameter")
	parameterOne.POST("GetTreeParameter", api.GetTreeParameter)
	parameterOne.POST("GetAllParameterInfo", api.GetAllParameterInfo)
	parameterOne.POST("GetParameterByID", api.GetParameterByID)
	parameterOne.POST("AddParameter", api.AddParameter)
	parameterOne.POST("UpdateParameter", api.UpdateParameter)
	parameterOne.POST("DeleteParameter", api.DeleteParameter)
	parameterOne.POST("GetParameterSelect", api.GetParameterSelect)
	billNoOne := router.Group("/BillNo")
	billNoOne.POST("GetAllBillNoInfo", api.GetAllBillNoInfo)
	billNoOne.POST("GetBillNoByID", api.GetBillNoByID)
	billNoOne.POST("AddBillNo", api.AddBillNo)
	billNoOne.POST("UpdateBillNo", api.UpdateBillNo)
	billNoOne.POST("DeleteBillNo", api.DeleteBillNo)
	noticeOne := router.Group("/Notice")
	noticeOne.POST("GetAllNoticeInfo", api.GetAllNoticeInfo)
	noticeOne.POST("AddNotice", api.AddNotice)
	noticeOne.POST("UpdateNotice", api.UpdateNotice)
	noticeOne.POST("DeleteNotice", api.DeleteNotice)
	noticeOne.POST("GetNoticeByID", api.GetNoticeByID)
	noticeOne.POST("GetNoticeItemByID", api.GetNoticeItemByID)
	noticeOne.POST("UpdateNoticeStatus", api.UpdateNoticeStatus)
	websocketOne := router.Group("/Websocket")
	websocketOne.GET("Ws", api.WsPage)
	return router
}
