basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /Login:
    post:
      description: 验证用户名密码有效性 accountName=aaa&passWord=base64(bbb)
      produces:
      - multipart/form-data
      responses:
        "200":
          description: '{"Code":200,"Data":{},"Message":"ok"}'
          schema:
            type: string
      summary: 登录验证服务
  /api/helper:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":,"Data":{},"Message":"ok"}'
          schema:
            type: string
      summary: Login
swagger: "2.0"
