basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: 目前仅仅是一个demo
  license: {}
  title: Rest API
  version: "1.0"
paths:
  /GetAllMenuInfo:
    post:
      consumes:
      - multipart/form-data
      description: '前台条件获取菜单信息 请求主体: base64(ParameterStr=aaaa&PageSize=10&CurrentPage=1)
        成功输出[]Menu'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ParameterStr
        in: formData
        name: ParameterStr
        required: true
        type: string
      - description: PageSize
        in: formData
        name: PageSize
        required: true
        type: integer
      - description: CurrentPage
        in: formData
        name: CurrentPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]Menu},"Message":""} or {"Code":-1,"Data":{},"Menu":"错误提示"}'
          schema:
            type: string
      summary: 前台条件获取菜单信息
      tags:
      - Menu
  /GetAllUserInfo:
    post:
      consumes:
      - multipart/form-data
      description: '前台条件获取用户信息 请求主体: base64(ParameterStr=aaaa&PageSize=10&CurrentPage=1)
        成功输出[]User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ParameterStr
        in: formData
        name: ParameterStr
        required: true
        type: string
      - description: PageSize
        in: formData
        name: PageSize
        required: true
        type: integer
      - description: CurrentPage
        in: formData
        name: CurrentPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]User},"Message":""} or {"Code":-1,"Data":{},"User":"错误提示"}'
          schema:
            type: string
      summary: 前台条件获取用户信息
      tags:
      - User
  /GetButtonByMenuIdAndUserId:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户菜单信息 请求主体:  base64(userId=aaaa&menuId=aaaa)  成功输出[]Button'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: userId
        in: formData
        name: userId
        required: true
        type: string
      - description: menuId
        in: formData
        name: menuId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]Button},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID和菜单ID获取相应权限的按钮信息
      tags:
      - Button
  /GetCascaderMenu:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户菜单信息 请求主体: Null  成功输出[]MenuTree'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]MenuTree},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户菜单信息
      tags:
      - User
  /GetMenuByID:
    post:
      consumes:
      - multipart/form-data
      description: '根据菜单ID获取菜单信息 请求主体: base64(ID=aaaa) 成功输出Menu'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ID
        in: formData
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{Menu},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据菜单ID获取菜单信息
      tags:
      - Menu
  /GetUserByID:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户信息 请求主体: base64(ID=aaaa) 成功输出User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ID
        in: formData
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{User},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户信息
      tags:
      - User
  /GetUserLogininfoByToken:
    post:
      consumes:
      - multipart/form-data
      description: 验证Token有效性 请求主体:为空 成功输出 空
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":"","Message":""}'
          schema:
            type: string
      summary: 验证Token有效性
      tags:
      - User
  /GetUserMenu:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户菜单信息 请求主体:  base64(userID=aaaa)  成功输出[]MenuTree'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: userID
        in: formData
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]MenuTree},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户菜单信息
      tags:
      - User
  /Login:
    post:
      consumes:
      - multipart/form-data
      description: 验证用户名密码有效性 accountName=aaa&passWord=base64(bbb) 成功输出Token
      parameters:
      - default: yxw
        description: 用户名
        in: formData
        name: accountName
        required: true
        type: string
      - default: "123"
        description: 密码
        in: formData
        name: passWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{Token},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 登录验证服务
      tags:
      - User
  /api/helper:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":,"Data":{},"Message":"ok"}'
          schema:
            type: string
      summary: Login
swagger: "2.0"
