basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: 目前仅仅是一个demo
  license: {}
  title: Rest API
  version: "1.0"
paths:
  /GetUserByID:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户信息 请求主体: ID=base64(aaaa) 成功输出User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ID
        in: formData
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{User},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户信息
      tags:
      - User
  /Login:
    post:
      consumes:
      - multipart/form-data
      description: 验证用户名密码有效性 accountName=aaa&passWord=base64(bbb) 成功输出Token
      parameters:
      - default: yxw
        description: 用户名
        in: formData
        name: accountName
        required: true
        type: string
      - default: "123"
        description: 密码
        in: formData
        name: passWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{Token},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 登录验证服务
      tags:
      - User
  /api/helper:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":,"Data":{},"Message":"ok"}'
          schema:
            type: string
      summary: Login
swagger: "2.0"
