basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: 目前仅仅是一个demo
  license: {}
  title: Rest API
  version: "1.0"
paths:
  /AddMenu:
    post:
      consumes:
      - multipart/form-data
      description: '新增菜单信息 请求主体: base64(str=aaaa) 成功输出null'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: str
        in: formData
        name: str
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 新增菜单信息
      tags:
      - Menu
  /AddUser:
    post:
      consumes:
      - multipart/form-data
      description: '新增用户信息 请求主体: base64(str=aaaa) 成功输出null'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: str
        in: formData
        name: str
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 新增用户信息
      tags:
      - User
  /DeleteMenu:
    post:
      consumes:
      - multipart/form-data
      description: '删除菜单信息 请求主体: base64(str=aaaa) 成功输出null'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: str
        in: formData
        name: str
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 删除菜单信息
      tags:
      - Menu
  /DeleteUser:
    post:
      consumes:
      - multipart/form-data
      description: '删除用户信息 请求主体: base64(str=aaaa) 成功输出null'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: str
        in: formData
        name: str
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 删除用户信息
      tags:
      - User
  /GetAllDeptForTransfer:
    post:
      consumes:
      - multipart/form-data
      description: '获取所有部门清单 请求主体: Null  成功输出[]TransferModel'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]TransferModel},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 获取所有部门清单
      tags:
      - Dept
  /GetAllMenuInfo:
    post:
      consumes:
      - multipart/form-data
      description: '前台条件获取菜单信息 请求主体: base64(ParameterStr=aaaa&PageSize=10&CurrentPage=1)
        成功输出[]Menu'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ParameterStr
        in: formData
        name: ParameterStr
        required: true
        type: string
      - description: PageSize
        in: formData
        name: PageSize
        required: true
        type: integer
      - description: CurrentPage
        in: formData
        name: CurrentPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]Menu},"Message":""} or {"Code":-1,"Data":{},"Menu":"错误提示"}'
          schema:
            type: string
      summary: 前台条件获取菜单信息
      tags:
      - Menu
  /GetAllMenuViewInfo:
    post:
      consumes:
      - multipart/form-data
      description: '前台条件获取菜单信息 请求主体: base64(ParameterStr=aaaa&PageSize=10&CurrentPage=1)
        成功输出[]Menu'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ParameterStr
        in: formData
        name: ParameterStr
        required: true
        type: string
      - description: PageSize
        in: formData
        name: PageSize
        required: true
        type: integer
      - description: CurrentPage
        in: formData
        name: CurrentPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]MenuView},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 前台条件获取菜单信息
      tags:
      - Menu
  /GetAllRoleForTransfer:
    post:
      consumes:
      - multipart/form-data
      description: '获取所有权限清单 请求主体: Null  成功输出[]TransferModel'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]TransferModel},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 获取所有权限清单
      tags:
      - Role
  /GetAllUserInfo:
    post:
      consumes:
      - multipart/form-data
      description: '前台条件获取用户信息 请求主体: base64(ParameterStr=aaaa&PageSize=10&CurrentPage=1)
        成功输出[]User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ParameterStr
        in: formData
        name: ParameterStr
        required: true
        type: string
      - description: PageSize
        in: formData
        name: PageSize
        required: true
        type: integer
      - description: CurrentPage
        in: formData
        name: CurrentPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]User},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 前台条件获取用户信息
      tags:
      - User
  /GetAllUserViewInfo:
    post:
      consumes:
      - multipart/form-data
      description: '前台条件获取用户信息 请求主体: base64(ParameterStr=aaaa&PageSize=10&CurrentPage=1)
        成功输出[]User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ParameterStr
        in: formData
        name: ParameterStr
        required: true
        type: string
      - description: PageSize
        in: formData
        name: PageSize
        required: true
        type: integer
      - description: CurrentPage
        in: formData
        name: CurrentPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]UserView},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 前台条件获取用户信息
      tags:
      - User
  /GetButtonByMenuIdAndUserId:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户菜单信息 请求主体:  base64(userId=aaaa&menuId=aaaa)  成功输出[]Button'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: userId
        in: formData
        name: userId
        required: true
        type: string
      - description: menuId
        in: formData
        name: menuId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]Button},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID和菜单ID获取相应权限的按钮信息
      tags:
      - Button
  /GetCascaderMenu:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户菜单信息 请求主体: Null  成功输出[]MenuTree'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]MenuTree},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户菜单信息
      tags:
      - User
  /GetDeptByUserIdForTransfer:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户权限信息 请求主体: base64(userId=aaaa) 成功输出字符串'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":"aaa,bbb,ccc","Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户权限信息
      tags:
      - Role
  /GetMenuAllCount:
    post:
      consumes:
      - multipart/form-data
      description: '获取菜单总条数 请求主体: Null  成功输出 int'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{int},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 获取菜单总条数
      tags:
      - User
  /GetMenuByID:
    post:
      consumes:
      - multipart/form-data
      description: '根据菜单ID获取菜单信息 请求主体: base64(ID=aaaa) 成功输出Menu'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ID
        in: formData
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{Menu},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据菜单ID获取菜单信息
      tags:
      - Menu
  /GetUserByID:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户信息 请求主体: base64(ID=aaaa) 成功输出User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: ID
        in: formData
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{User},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户信息
      tags:
      - User
  /GetUserLogininfoByToken:
    post:
      consumes:
      - multipart/form-data
      description: 验证Token有效性 请求主体:为空 成功输出 空
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":"","Message":""}'
          schema:
            type: string
      summary: 验证Token有效性
      tags:
      - User
  /GetUserMenu:
    post:
      consumes:
      - multipart/form-data
      description: '根据用户ID获取用户菜单信息 请求主体:  base64(userID=aaaa)  成功输出[]MenuTree'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: userID
        in: formData
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{[]MenuTree},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 根据用户ID获取用户菜单信息
      tags:
      - User
  /Login:
    post:
      consumes:
      - multipart/form-data
      description: 验证用户名密码有效性 accountName=aaa&passWord=base64(bbb) 成功输出Token
      parameters:
      - default: yxw
        description: 用户名
        in: formData
        name: accountName
        required: true
        type: string
      - default: "123"
        description: 密码
        in: formData
        name: passWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{Token},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 登录验证服务
      tags:
      - User
  /SetUserDept:
    post:
      consumes:
      - multipart/form-data
      description: '设置用户部门 请求主体: base64(ID=aaaa) 成功输出User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: 用户ID
        in: formData
        name: userId
        required: true
        type: string
      - description: 部门ID，拼着接字符串
        in: formData
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 设置用户部门
      tags:
      - User
  /SetUserRole:
    post:
      consumes:
      - multipart/form-data
      description: '设置设置用户权限用户部门 请求主体: base64(ID=aaaa) 成功输出User'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: 用户ID
        in: formData
        name: userId
        required: true
        type: string
      - description: 权限ID，拼着接字符串
        in: formData
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 设置用户权限
      tags:
      - User
  /UpdateMenu:
    post:
      consumes:
      - multipart/form-data
      description: '修改菜单信息 请求主体: base64(str=aaaa) 成功输出null'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: str
        in: formData
        name: str
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 修改菜单信息
      tags:
      - Menu
  /UpdateUser:
    post:
      consumes:
      - multipart/form-data
      description: '修改用户信息 请求主体: base64(str=aaaa) 成功输出null'
      parameters:
      - description: Token
        in: formData
        name: Token
        required: true
        type: string
      - description: str
        in: formData
        name: str
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":1,"Data":{},"Message":""} or {"Code":-1,"Data":{},"Message":"错误提示"}'
          schema:
            type: string
      summary: 修改用户信息
      tags:
      - User
  /api/helper:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":,"Data":{},"Message":"ok"}'
          schema:
            type: string
      summary: Login
swagger: "2.0"
